build: install
	@echo "Building web client..."
	@npm run build

install:
	@echo "Installing web client dependencies..."
	@npm install

clean:
	@echo "Cleaning web client..."
	@rm -rf bin build node_modules

.PHONY: build install clean
