import RL.Parser (sparse, parseIdentifier)
main = do
let parse = putStrLn . (sparse parseIdentifier)
parse "a"
parse "A"
parse "_"
parse "_a"
parse "some_variable"
parse "some_variable_1"
parse "a[0]"
parse "A[0]"
parse "_[0]"
parse "_a[0]"
parse "some_variable[0]"
parse "some_variable_1[0]"
parse "a[1+a]"
parse "A[1+a]"
parse "_[1+a]"
parse "_a[1+a]"
parse "some_variable[1+a]"
parse "some_variable_1[1+a]"
parse "a[true]"
parse "A[true]"
parse "_[true]"
parse "_a[true]"
parse "some_variable[true]"
parse "some_variable_1[true]"
