name:                src
version:             0.1.0.0
github:              "githubuser/src"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/src#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.0
- cmdargs >= 0.10.20
- monad-loops >= 0.4.3
- unordered-containers >= 0.2.9
- containers >= 0.5.10.2
- mtl >= 2.2
- filepath >= 1.4

library:
  source-dirs: src

executables:
  rl:
    main:                src/RL/Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optP-Wno-nonportable-include-path
    - -main-is RL.Main.main
    dependencies:
    - src
  srl:
    main:                src/SRL/Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optP-Wno-nonportable-include-path
    - -main-is SRL.Main.main
    dependencies:
    - src

tests:
  src-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - src
    - Glob
